services:
  - type: web
    name: ig-selenium-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: BOT_TOKEN
        value: 8098677151:AAHw3ofWspeagUJWjWejk91whH9z9y_PoYA
      - key: CHAT_ID
        value: 802683583
      - key: IG_USERNAME
        value: ansil.666
      - key: IG_PASSWORD
        value: Ansil666nigga6
