services:
  - type: web
    name: ig-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
      - key: CHAT_ID
        value: your_chat_id_here
      - key: IG_USERNAME
        value: your_instagram_username
      - key: IG_PASSWORD
        value: your_instagram_password 
