services:
  - type: web
    name: ig-selenium-tracker
    env: python
    buildCommand: |
      apt-get update && apt-get install -y chromium-browser
      pip install -r requirements.txt
    startCommand: bash start.sh
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: IG_USERNAME
        sync: false
      - key: IG_PASSWORD
        sync: false
