services:
  - type: web
    name: ig-selenium-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: BOT_TOKEN
        value: 
      - key: CHAT_ID
        value:
      - key: IG_USERNAME
        value: 
      - key: IG_PASSWORD
        value: 
